# Generated by Django 3.0.3 on 2020-04-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmg', '0002_auto_20200311_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.FloatField()),
                ('columnaA', models.FloatField()),
                ('columnaB', models.FloatField()),
                ('columnaC', models.FloatField()),
                ('columnaD', models.FloatField()),
                ('columnaE', models.FloatField()),
                ('columnaF', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='TablaA',
        ),
        migrations.DeleteModel(
            name='TablaB',
        ),
        migrations.DeleteModel(
            name='TablaC',
        ),
        migrations.DeleteModel(
            name='TablaD',
        ),
        migrations.DeleteModel(
            name='TablaE',
        ),
        migrations.DeleteModel(
            name='TablaF',
        ),
    ]
