# Generated by Django 3.0.3 on 2020-04-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgmg', '0005_auto_20200415_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='columnaA',
            field=models.FloatField(default=-10, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='columnaB',
            field=models.FloatField(default=-10, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='columnaC',
            field=models.FloatField(default=-10, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='columnaD',
            field=models.FloatField(default=-10, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='columnaE',
            field=models.FloatField(default=-10, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='columnaF',
            field=models.FloatField(default=-10, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='tiempo',
            field=models.FloatField(default=-10, null=True),
        ),
    ]
